### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by 8bitgentleman** [mislavcimpersak/anydo-widget#2]
Is it possible to use this widget if you login to any.do via a google account?

**Comment by mislavcimpersak** [comment]
unfortunately no. authentification is handled differently. i'm not sure how should a widget request a token from google :-/

**Comment by 8bitgentleman** [comment]
Oh well, it's still a cool little widget though.  Thanks

**Comment by mislavcimpersak** [comment]
Thanks mate. Cheers
